name: Auto cancel
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ gihub.ref }}
  cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"    
      - run: sleep 120