name: Concurrency
on: push
concurrency: ${{ github.workflow }}
jobs:
  sleep:
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKFLOW: ${{ github.workflow }}
      GITHUB_REF: ${{ github.ref }}
    steps:
      - run: echo "${GITHUB_WORKFLOW}, ${GITHUB_REF}"
      - run: sleep 120