name: Concurrency
on: push
concurrency: ${{ github.workflow }}
jobs:
  sleep:
    runs-on: ubuntu-latest
    env:
      GITHUB_WORFLOW: ${{ github.workflow }}
      GITHUB_REF: ${{ github.ref }}
    steps:
      - run: sleep 120